# Generated by Django 3.1 on 2020-09-09 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('shortName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=256)),
                ('view', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=256)),
                ('privacy', models.CharField(max_length=120)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('view', models.IntegerField(blank=True, default=0)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Politricks.location')),
                ('partyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Politricks.party')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.ManyToManyField(to='Politricks.Post')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Politricks.tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('photo', models.ImageField(blank=True, upload_to='profile_pics')),
                ('tag', models.ManyToManyField(to='Politricks.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Politricks.post')),
                ('supportCnt', models.ManyToManyField(related_name='post_react_user', to='Politricks.UserInfo')),
                ('unSupportCnt', models.ManyToManyField(blank=True, related_name='post_antireact_user', to='Politricks.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='postTag',
            field=models.ManyToManyField(to='Politricks.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Politricks.userinfo'),
        ),
        migrations.CreateModel(
            name='PartyTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=205)),
                ('description', models.CharField(max_length=250)),
                ('rating', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('lastmodified', models.DateTimeField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Politricks.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Politricks.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postDate', models.DateTimeField(blank=True, null=True)),
                ('content', models.CharField(max_length=256)),
                ('postID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Politricks.post')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Politricks.userinfo')),
            ],
        ),
    ]
