# Generated by Django 3.1 on 2020-09-09 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Politricks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Politricks.status'),
        ),
    ]
