# Generated by Django 3.1 on 2020-09-09 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Politricks', '0002_userinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Politricks.status'),
        ),
    ]
