# Generated by Django 3.1 on 2020-09-24 22:09

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Politricks', '0006_post_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
