# Generated by Django 3.1 on 2020-09-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Politricks', '0007_auto_20200925_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='post_photos'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
